# LAB10  Introduction to numerical analysis – Week 1 – Peer-graded Assignment: Solve a quadratic equation (Groups in Class)

**Universidad Nacional de Colombia - Sede Bogotá**
 
 _**Metodos Numericos**_

 **Docente:** German Hernandez

 **Estudiante:**
 * Luis Miguel Báez Aponte - lmbaeza@unal.edu.co

# I. $LU$ factorization of a square matrix

Consider a simple naive implementation of the LU decomposition. 

Note that we're using the `numpy` arrays to represent matrices [do **not** use `np.matrix`].

In [113]:
import numpy as np

def diy_lu(a):
    """Construct the LU decomposition of the input matrix.
    
    Naive LU decomposition: work column by column, accumulate elementary triangular matrices.
    No pivoting.
    """
    N = a.shape[0]
    
    u = a.copy()
    L = np.eye(N)
    for j in range(N-1):
        lam = np.eye(N)
        gamma = u[j+1:, j] / u[j, j]
        lam[j+1:, j] = -gamma
        u = lam @ u

        lam[j+1:, j] = gamma
        L = L @ lam
    return L, u

In [114]:
# Now, generate a full rank matrix and test the naive implementation

import numpy as np

N = 6
a = np.zeros((N, N), dtype=float)
for i in range(N):
    for j in range(N):
        a[i, j] = 3. / (0.6*i*j + 1)

np.linalg.matrix_rank(a)

6

In [115]:
# Tweak the printing of floating-point numbers, for clarity
np.set_printoptions(precision=3)

In [116]:
L, u = diy_lu(a)

print(L, "\n")
print(u, "\n")

# Quick sanity check: L times U must equal the original matrix, up to floating-point errors.
print(L@u - a)

[[1.    0.    0.    0.    0.    0.   ]
 [1.    1.    0.    0.    0.    0.   ]
 [1.    1.455 1.    0.    0.    0.   ]
 [1.    1.714 1.742 1.    0.    0.   ]
 [1.    1.882 2.276 2.039 1.    0.   ]
 [1.    2.    2.671 2.944 2.354 1.   ]] 

[[ 3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00]
 [ 0.000e+00 -1.125e+00 -1.636e+00 -1.929e+00 -2.118e+00 -2.250e+00]
 [ 0.000e+00  0.000e+00  2.625e-01  4.574e-01  5.975e-01  7.013e-01]
 [ 0.000e+00  2.220e-16  0.000e+00 -2.197e-02 -4.480e-02 -6.469e-02]
 [ 0.000e+00 -4.528e-16  0.000e+00  6.939e-18  8.080e-04  1.902e-03]
 [ 0.000e+00  4.123e-16  0.000e+00 -1.634e-17  0.000e+00 -1.585e-05]] 

[[ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00 -1.110e-16  1.110e-16  1.110e-16 -5.551e-17]
 [ 0.000e+00  0.000e+00  3.331e-16 -2.220e-16 -5.551e-17  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00 -1.110e-16 -1.665e-16  0.000e+00]
 

# II. The need for pivoting

Let's tweak the matrix a little bit, we only change a single element:

In [117]:
a1 = a.copy()
a1[1, 1] = 3

Resulting matix still has full rank, but the naive LU routine breaks down.

In [118]:
np.linalg.matrix_rank(a1)

6

In [119]:
l, u = diy_lu(a1)

print(l, u)

[[nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]] [[nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: RuntimeWarning: divide by zero encountered in true_divide
  from ipykernel import kernelapp as app
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: RuntimeWarning: invalid value encountered in matmul
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: RuntimeWarning: invalid value encountered in matmul
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in true_divide
  from ipykernel import kernelapp as app


### Test II.1

For a naive LU decomposition to work, all leading minors of a matrix should be non-zero. Check if this requirement is satisfied for the two matrices `a` and `a1`.

(20% of the grade)

In [120]:
def leading_minors_test(A):
  """
  Function to check all leading Minors of a Matrix not equal to 0
  """
  N = A.shape[0]
  u = A.copy()
  L = np.eye(N)
  for j in range(N-1):
      lam = np.eye(N)
      if u[j, j] == 0.0:
        return False
      gamma = u[j+1:, j] / u[j, j]
      lam[j+1:, j] = -gamma
      u = lam @ u
  return True

leading_minors_test(a), leading_minors_test(a1)

(True, False)

### Test II.2

1. Modify the `diy_lu` routine to implement column pivoting. Keep track of pivots, you can either construct a permutation matrix, or a swap array (your choice).

(40% of the grade)

2. Implement a function to reconstruct the original matrix from a decompositon. Test your routines on the matrices `a` and `a1`.

(40% of the grade)

# Answer 1

In [121]:
def diy_lu_column_pivot(a):
  """Construct the LU decomposition of the input matrix.

  LU decomposition with pivot: work column by column, accumulate elementary triangular matrices L @ np.transpose(Pj) .
  """
  N = a.shape[0]
  u = a.copy()
  L = np.eye(N)

  P1 = np.eye(N) # Permutacion Inicial 1
  P2 = np.eye(N) # Permutacion Inicial 2

  for j in range(N-1):
    lam = np.eye(N)
    i = j
    while (u[i, i] == 0.0 and i < N-1):
      tmp = np.argmax(abs(u[i:,i])) + i
      P2[i], P2[tmp] = P2[tmp], P2[i].copy()
      u = P2 @ u
      i += 1
    gamma = u[j+1:, j] / u[j, j]
    lam[j+1:, j] = -gamma
    u = lam @ u

    lam[j+1:, j] = gamma
    L = L @ lam @ P1
  return  L, u, P1

In [122]:
N = 6
a = np.zeros((N, N), dtype=float)
for i in range(N):
    for j in range(N):
        a[i, j] = 3. / (0.6*i*j + 1)

L, u, P = diy_lu_column_pivot(a)

print("L\n",L, "\n")
print("u\n",u, "\n")
print("L@u\n", L@u, "\n")
print("a\n",a, "\n")
print("P\n", P, "\n")
print("a\n",a, "\n")

L
 [[1.    0.    0.    0.    0.    0.   ]
 [1.    1.    0.    0.    0.    0.   ]
 [1.    1.455 1.    0.    0.    0.   ]
 [1.    1.714 1.742 1.    0.    0.   ]
 [1.    1.882 2.276 2.039 1.    0.   ]
 [1.    2.    2.671 2.944 2.354 1.   ]] 

u
 [[ 3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00]
 [ 0.000e+00 -1.125e+00 -1.636e+00 -1.929e+00 -2.118e+00 -2.250e+00]
 [ 0.000e+00  0.000e+00  2.625e-01  4.574e-01  5.975e-01  7.013e-01]
 [ 0.000e+00  2.220e-16  0.000e+00 -2.197e-02 -4.480e-02 -6.469e-02]
 [ 0.000e+00 -4.528e-16  0.000e+00  6.939e-18  8.080e-04  1.902e-03]
 [ 0.000e+00  4.123e-16  0.000e+00 -1.634e-17  0.000e+00 -1.585e-05]] 

L@u
 [[3.    3.    3.    3.    3.    3.   ]
 [3.    1.875 1.364 1.071 0.882 0.75 ]
 [3.    1.364 0.882 0.652 0.517 0.429]
 [3.    1.071 0.652 0.469 0.366 0.3  ]
 [3.    0.882 0.517 0.366 0.283 0.231]
 [3.    0.75  0.429 0.3   0.231 0.188]] 

a
 [[3.    3.    3.    3.    3.    3.   ]
 [3.    1.875 1.364 1.071 0.882 0.75 ]
 [3.    1.364 0.8

In [123]:
a1 = a.copy()
a1[1, 1] = 3

L, u , P = diy_lu_column_pivot(a1)

print("L\n",L, "\n")
print("u\n",u, "\n")
print("L@u\n", L@u, "\n")
print("a\n",a, "\n")
print("P\n", P, "\n")
print("a\n",a, "\n")

L
 [[1.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [1.000e+00 1.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [1.000e+00 7.273e-01 1.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [1.000e+00 8.571e-01 5.807e-01 1.000e+00 0.000e+00 0.000e+00]
 [1.000e+00 9.412e-01 2.529e-01 6.797e-01 1.000e+00 0.000e+00]
 [1.000e+00 0.000e+00 6.611e+00 9.937e+01 2.597e+03 1.000e+00]] 

u
 [[ 3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00]
 [ 0.000e+00 -2.250e+00 -2.571e+00 -2.700e+00 -2.769e+00 -2.812e+00]
 [ 0.000e+00  0.000e+00 -2.475e-01 -3.842e-01 -4.688e-01 -5.260e-01]
 [ 0.000e+00  2.220e-16  0.000e+00  6.152e-03  1.172e-02  1.617e-02]
 [ 0.000e+00 -1.509e-16  0.000e+00  0.000e+00 -7.044e-05 -1.585e-04]
 [ 0.000e+00  3.699e-13  0.000e+00  0.000e+00  0.000e+00  3.202e-02]] 

L@u
 [[3.    3.    3.    3.    3.    3.   ]
 [3.    0.75  0.429 0.3   0.231 0.188]
 [3.    1.364 0.882 0.652 0.517 0.429]
 [3.    1.071 0.652 0.469 0.366 0.3  ]
 [3.    0.882 0.517 0.366 0.283 0.2

In [124]:
a2 = np.array([[4,3,1], [5,7,0], [9,9,3], [8,2,4]])

L, u, P = diy_lu_column_pivot(a2)

print("L\n",L, "\n")
print("u\n",u, "\n")
print("L@u\n", L@u, "\n")
print("a\n",a, "\n")
print("P\n", P, "\n")
print("P@L@u\n", P@L@u, "\n")
print("a\n",a, "\n")

L
 [[ 1.     0.     0.     0.   ]
 [ 1.25   1.     0.     0.   ]
 [ 2.25   0.692  1.     0.   ]
 [ 2.    -1.231  0.286  1.   ]] 

u
 [[ 4.     3.     1.   ]
 [ 0.     3.25  -1.25 ]
 [ 0.     0.     1.615]
 [ 0.     0.     0.   ]] 

L@u
 [[4. 3. 1.]
 [5. 7. 0.]
 [9. 9. 3.]
 [8. 2. 4.]] 

a
 [[3.    3.    3.    3.    3.    3.   ]
 [3.    1.875 1.364 1.071 0.882 0.75 ]
 [3.    1.364 0.882 0.652 0.517 0.429]
 [3.    1.071 0.652 0.469 0.366 0.3  ]
 [3.    0.882 0.517 0.366 0.283 0.231]
 [3.    0.75  0.429 0.3   0.231 0.188]] 

P
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

P@L@u
 [[4. 3. 1.]
 [5. 7. 0.]
 [9. 9. 3.]
 [8. 2. 4.]] 

a
 [[3.    3.    3.    3.    3.    3.   ]
 [3.    1.875 1.364 1.071 0.882 0.75 ]
 [3.    1.364 0.882 0.652 0.517 0.429]
 [3.    1.071 0.652 0.469 0.366 0.3  ]
 [3.    0.882 0.517 0.366 0.283 0.231]
 [3.    0.75  0.429 0.3   0.231 0.188]] 



# Answer 2

In [125]:
def diy_lu_column_pivot_reconstruct(a):
    """Construct the LU decomposition of the input matrix.
    
    LU decomposition with pivot: work column by column, accumulate elementary triangular matrices L @ np.transpose(Pj) .
    """
    N = a.shape[0]
    u = a.copy()
    L = np.eye(N)
    perm = np.eye(N)
    for j in range(0, N-1):
        i = np.argmax(np.abs(u[j:, j])) + j
        u[[j, i]] = u[[i, j]]
        L1 = np.eye(N)
        gamma = u[j+1:, j] / u[j, j]
        L1[j+1:, j] = -gamma
        u = L1 @ u
        L1[j+1:, j] = gamma
        L = L @ L1
        P1 = np.eye(N)
        P1[[j, i]] = P1[[i, j]]
        perm = perm @ np.transpose(P1)
    return L, u

In [126]:
N = 6
a = np.zeros((N, N), dtype=float)
for i in range(N):
    for j in range(N):
        a[i, j] = 3. / (0.6*i*j + 1)

L, u = diy_lu_column_pivot_reconstruct(a)

print("L\n",L, "\n")
print("u\n",u, "\n")
print("L@u\n", L@u, "\n")
print("a\n",a, "\n")

L
 [[1.    0.    0.    0.    0.    0.   ]
 [1.    1.    0.    0.    0.    0.   ]
 [1.    0.727 1.    0.    0.    0.   ]
 [1.    0.857 0.41  1.    0.    0.   ]
 [1.    0.941 0.178 0.426 1.    0.   ]
 [1.    0.5   0.706 0.835 0.789 1.   ]] 

u
 [[ 3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00]
 [ 0.000e+00 -2.250e+00 -2.571e+00 -2.700e+00 -2.769e+00 -2.812e+00]
 [ 0.000e+00  0.000e+00 -3.506e-01 -5.786e-01 -7.330e-01 -8.438e-01]
 [ 0.000e+00  0.000e+00  2.776e-17  2.421e-02  4.866e-02  6.961e-02]
 [ 0.000e+00  2.220e-16 -2.317e-17  0.000e+00 -6.462e-04 -1.516e-03]
 [ 0.000e+00 -1.751e-16  6.463e-18  0.000e+00  0.000e+00  6.730e-06]] 

L@u
 [[3.    3.    3.    3.    3.    3.   ]
 [3.    0.75  0.429 0.3   0.231 0.188]
 [3.    1.364 0.779 0.458 0.253 0.111]
 [3.    1.071 0.652 0.473 0.375 0.313]
 [3.    0.882 0.517 0.366 0.283 0.23 ]
 [3.    1.875 1.467 1.262 1.138 1.055]] 

a
 [[3.    3.    3.    3.    3.    3.   ]
 [3.    1.875 1.364 1.071 0.882 0.75 ]
 [3.    1.364 0.8

In [127]:
a1 = a.copy()
a1[1, 1] = 3

L, u, = diy_lu_column_pivot_reconstruct(a1)

print("L\n",L, "\n")
print("u\n",u, "\n")
print("L@u\n", L@u, "\n")
print("a2\n",a1, "\n")

# Quick sanity check: L times U must equal the original matrix, up to floating-point errors.
# print("L@u - a1\n",L@u - a1, "\n")

L
 [[1.    0.    0.    0.    0.    0.   ]
 [1.    1.    0.    0.    0.    0.   ]
 [1.    0.727 1.    0.    0.    0.   ]
 [1.    0.857 0.088 1.    0.    0.   ]
 [1.    0.941 0.038 0.208 1.    0.   ]
 [1.    0.    0.151 0.514 0.641 1.   ]] 

u
 [[ 3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00]
 [ 0.000e+00 -2.250e+00 -2.571e+00 -2.700e+00 -2.769e+00 -2.812e+00]
 [ 0.000e+00  0.000e+00 -1.636e+00 -1.929e+00 -2.118e+00 -2.250e+00]
 [ 0.000e+00  0.000e+00  2.776e-17 -9.247e-02 -1.485e-01 -1.856e-01]
 [ 0.000e+00  2.220e-16 -1.427e-17  0.000e+00  1.841e-03  3.821e-03]
 [ 0.000e+00 -1.424e-16  3.391e-18  0.000e+00  0.000e+00 -1.233e-05]] 

L@u
 [[ 3.     3.     3.     3.     3.     3.   ]
 [ 3.     0.75   0.429  0.3    0.231  0.188]
 [ 3.     1.364 -0.506 -0.892 -1.132 -1.295]
 [ 3.     1.071  0.652  0.424  0.292  0.206]
 [ 3.     0.882  0.517  0.366  0.284  0.232]
 [ 3.     3.     2.752  2.661  2.605  2.567]] 

a2
 [[3.    3.    3.    3.    3.    3.   ]
 [3.    3.    1.364

In [128]:
a2 = np.array([[4,3,1], [5,7,0], [9,9,3], [8,2,4]])

L, u, = diy_lu_column_pivot_reconstruct(a2)

print("L\n",L, "\n")
print("u\n",u, "\n")
print("L@u\n", L@u, "\n")
print("a2\n",a2, "\n")

# Quick sanity check: L times U must equal the original matrix, up to floating-point errors.
print("L@u - a2\n",L@u - a2, "\n")

L
 [[ 1.     0.     0.     0.   ]
 [ 0.556  1.     0.     0.   ]
 [ 0.444  0.167  1.     0.   ]
 [ 0.889 -0.333  0.455  1.   ]] 

u
 [[ 9.     9.     3.   ]
 [ 0.    -6.     1.333]
 [ 0.     0.    -1.222]
 [ 0.     0.     0.   ]] 

L@u
 [[ 9.     9.     3.   ]
 [ 5.    -1.     3.   ]
 [ 4.     3.     0.333]
 [ 8.    10.     1.667]] 

a2
 [[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]] 

L@u - a2
 [[ 5.     6.     2.   ]
 [ 0.    -8.     3.   ]
 [-5.    -6.    -2.667]
 [ 0.     8.    -2.333]] 

